### ISSUE TITLE
servers.py

### ISSUE THREAD

**Issue by jeromim** [cstewart90/minqlx-plugins#5]
I run the !servers command and this error appears.

Exception in thread get_servers-14-minqlxthread:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./minqlx-plugins/servers.py", line 69, in get_servers
    hostname, players = self.get_server_info(server)
  File "./minqlx-plugins/servers.py", line 93, in get_server_info
    info = server.get_info()
AttributeError: 'ServerQuerier' object has no attribute 'get_info'
pedreiro^7: !servers

**Comment by cstewart90** [comment]
The python-valve library I use updated. http://python-valve.readthedocs.io/en/stable/source.html  
``get_info()`` was renamed to ``info()``.

**Quick fix**
 - change line 93 so it reads ```info = server.info()```

I will do it shortly in the plugin and fix pip install instructions.
